INSERT INTO diseases (name) VALUES ('Leucemia');
INSERT INTO diseases (name) VALUES ('Linfoma');
INSERT INTO diseases (name) VALUES ('Tumores del Sistema Nervioso Central');
INSERT INTO diseases (name) VALUES ('Neuroblastoma');
INSERT INTO diseases (name) VALUES ('Tumores Óseos');
INSERT INTO diseases (name) VALUES ('Sarcomas de Partes blandas');
INSERT INTO diseases (name) VALUES ('Retinoblastomas');
INSERT INTO diseases (name) VALUES ('Tumor de células Germinales');
INSERT INTO diseases (name) VALUES ('Tumor Hepático');
INSERT INTO diseases (name) VALUES ('Histiocitosis de células de Langerhans');