INSERT INTO symptoms (name, alias, type) VALUES ('Fiebre mayor a 7 días sin causa conocida', 's1', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Dolor de cabeza persistente y progresivo', 's2', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Dolores óseos moderados a severo', 's3', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Petequias, moretones o sangrado anormal', 's4', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Palidez conjuntival y/o palmar severa', 's5', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Leucocoria, Estrabismo , Aniridia, Heterocromía, Hifema, Proptosis', 's6', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Ganglios mayores 2.5cm, no dolorosos, duros, con más de 4 semanas de evolución y sin signos de inflamación', 's7', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Convulsión sin fiebre, ni enfermedad neurológica de base', 's8', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Debilidad unilateral', 's9', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Pérdida de equilibrio al caminar o aumento de base de sustentación', 's10', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Dificultad para hablar', 's11', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Inicio súbito de visión borrosa, doble o ceguera', 's12', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Masa palpable o incremento de volumen en alguna región del cuerpo sin signos de inflamación', 's13', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Hepatomegalia y/o esplenomegalia', 's14', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Dolor y distensión abdominal, pérdida de peso, rechazo a la alimentación.', 's15', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Dolor pélvico, estreñimiento y trastornos genitourinarios, dolor testicular', 's16', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Vómitos', 's17', 'URG');
INSERT INTO symptoms (name, alias, type) VALUES ('Pérdida de apetito, pérdida de peso o cansancio en los últimos 3 meses', 's18', 'NOURG');
INSERT INTO symptoms (name, alias, type) VALUES ('Sudoración nocturna importante, sin causa aparente.', 's19', 'NOURG');
INSERT INTO symptoms (name, alias, type) VALUES ('Palidez palmar o conjuntival leve.', 's20', 'NOURG');
INSERT INTO symptoms (name, alias, type) VALUES ('Linfadenopatía dolorosa o con evolución < 4 semanas o con diámetro ≤ 2,5 cm o consistencia no dura.', 's21', 'NOURG');
INSERT INTO symptoms (name, alias, type) VALUES ('Aumento de volumen en cualquier región del cuerpo con signos de inflamación.', 's22', 'NOURG');
INSERT INTO symptoms (name, alias, type) VALUES ('Otorrea a repetición.', 's23', 'NOURG');
INSERT INTO symptoms (name, alias, type) VALUES ('Eritema perianal persistente', 's24', 'NOURG');
INSERT INTO symptoms (name, alias, type) VALUES ('Dermatitis seborreica persistente', 's25', 'NOURG');